# This is a basic workflow to help you get started with Actions

name: Process Learning Outcomes

# Controls when the action will run. 
on: 
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  process:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: execute script
        run: |
          python scripts/process_outcomes.py
          
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Run GH Action to process learning outcomes'
